# Generated by Django 4.2.2 on 2023-06-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("hardcopy", "hardcopy"), ("softcopy", "softcopy")],
                max_length=100,
            ),
        ),
    ]
