# Generated by Django 4.2.2 on 2023-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="userprofile/download.jpeg", upload_to="userprofile"
            ),
        ),
    ]
